### ISSUE TITLE
一直报缺少“sass”依赖  跑不起来是什么原因呢，已经多次使用pnpm add sass  安装了该依赖的。

### ISSUE THREAD

**Issue by zouxingjie** [xiaoxian521/vue-pure-admin#246]
ready in 5565ms.

Preprocessor dependency "sass" not found. Did you install it?
Preprocessor dependency "sass" not found. Did you install it? (x2)
Preprocessor dependency "sass" not found. Did you install it? (x3)
下午1:51:47 [vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?
  Plugin: vite:css
  File: F:/练习/vue-pure-admin/vue-pure-admin/src/style/index.scss
      at loadPreprocessor (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:28263:19)
      at scss (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:28274:20)
      at compileCSS (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:27902:40)
      at async TransformContext.transform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:27526:55)
      at async Object.transform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36672:30)
      at async doTransform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:55662:29)
下午1:52:09 [vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?
  Plugin: vite:css
  File: F:/练习/vue-pure-admin/vue-pure-admin/src/plugins/vxe-table/index.scss
      at loadPreprocessor (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:28263:19)
      at scss (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:28274:20)
      at compileCSS (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:27902:40)
      at async TransformContext.transform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:27526:55)
      at async Object.transform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36672:30)
      at async doTransform (F:\练习\vue-pure-admin\vue-pure-admin\node_modules\.pnpm\vite@2.9.5_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:55662:29)
下午1:52:10 [vite] ✨ new dependencies optimized: element-plus/es/components/tag/style/css, element-plus/es/components/config-provider/style/css, element-plus/es/components/affix/style/css, element-plus/es/components/skeleton/style/css, element-plus/es/components/breadcrumb/style/css, ...and 57 more

**Comment by xiaoxian521** [comment]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/44761321/164160196-9784df0d-eabc-4465-a2a3-905ae6fde26a.png">
看文档要好好看呀 我特意备注三遍
