### ISSUE TITLE
拷贝项目到另外一个目录下，重新安装依赖，运行报错

### ISSUE THREAD

**Issue by doudou1926** [xiaoxian521/vue-pure-admin#274]
将此项目拷贝到另外一个目录下，安装依赖正常，当pnpm run dev 后报错：
[vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?
  Plugin: vite:css
  File: D:/Code/vue新架构/pure-admin-thin/src/style/index.scss
      at loadPreprocessor (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:30390:19)
      at scss (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:30401:20)
      at compileCSS (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:30029:40)
      at async TransformContext.transform (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:29653:55)
      at async Object.transform (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:38817:30)
      at async doTransform (D:\Code\vue新架构\pure-admin-thin\node_modules\.pnpm\vite@2.9.6_sass@1.50.1\node_modules\vite\dist\node\chunks\dep-3397b401.js:55749:29)

确定sass已安装，重新安装sass 也不行

**Comment by xiaoxian521** [comment]
看看文档啊 多看文档
