### ISSUE TITLE
pnpm report

### ISSUE THREAD

**Issue by figo361** [xiaoxian521/vue-pure-admin#396]
**Describe the bug**
goto: pnpm report
rendering chunks (218)...[visualizer] spawn EPERM
error during build:
Error: spawn EPERM
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at baseOpen (D:\web_farme\vue-admin\node_modules\.pnpm\open@8.4.0\node_modules\open\index.js:205:34)
    at async Object.generateBundle (D:\web_farme\vue-admin\node_modules\.pnpm\rollup-plugin-visualizer@5.8.3\node_modules\rollup-plugin-visualizer\dist\plugin\index.js:145:21)
    at async Bundle.generate (file:///D:/web_farme/vue-admin/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:15990:9)
    at async file:///D:/web_farme/vue-admin/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23754:27
    at async catchUnfinishedHookActions (file:///D:/web_farme/vue-admin/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23088:20)
    at async doBuild (file:///D:/web_farme/vue-admin/node_modules/.pnpm/vite@3.1.8_sass@1.56.1+terser@5.16.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45831:20)
    at async build (file:///D:/web_farme/vue-admin/node_modules/.pnpm/vite@3.1.8_sass@1.56.1+terser@5.16.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45662:16)
    at async CAC.<anonymous> (file:///D:/web_farme/vue-admin/node_modules/.pnpm/vite@3.1.8_sass@1.56.1+terser@5.16.0/node_modules/vite/dist/node/cli.js:748:9)
 ELIFECYCLE  Command failed with exit code 1.

**Desktop (please complete the following information):**
 - OS: [window10]
 - Browser [chrome]
 - Version [108.0.5359.99]

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/start/#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

check `node` and `pnpm` version
