### ISSUE TITLE
在pure-admin-thin中引入这里的PureTableBar引起报错

### ISSUE THREAD

**Issue by fietiger** [xiaoxian521/vue-pure-admin#434]
**错误描述**
这里的PureTableBar比较好用，想要在pure-admin-thin中使用，但引发了错误，使用PureTableBar的页面不显示（空白）。在控制台能看到两个错误。

**复现步骤**
1. 将vue-pure-admin中的文件夹RePureTableBar复制到pure-admin-thin项目中对应的位置，
2. 在页面上导入 PureTableBar `import { PureTableBar } from "@/components/RePureTableBar";`
3. 使用 PureTableBar 
``` VUE
<script lang="ts" setup>
import { PureTableBar } from "@/components/RePureTableBar";

const tableData = [
  {
    date: "2016-05-03",
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles"
  }
];

const indexMethod = (index: number) => {
  return index * 2;
};
const columns: TableColumnList = [
  {
    type: "index",
    index: indexMethod
  },
  {
    label: "日期",
    prop: "date"
  },
  {
    label: "姓名",
    prop: "name"
  },
  {
    label: "地址",
    prop: "address"
  }
];
</script>
<template>
  <div>
    <h1>Users</h1>
    <PureTableBar title="用户列表">
      <pure-table :data="tableData" :columns="columns" />
    </PureTableBar>
  </div>
</template>

```
4. 刷新页面，有时需要重启服务。在导航到这个页面时候出现空白页面，在控制台能看到以下错误信息。
``` LOG
bar.tsx:113行 
Uncaught (in promise) TypeError: slots?.buttons is not a function
    at Proxy.<anonymous> (bar.tsx:113:46)
    at renderComponentRoot (runtime-core.esm-bundler.js:898:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5631:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5759:9)
    at mountComponent (runtime-core.esm-bundler.js:5541:9)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at mountChildren (runtime-core.esm-bundler.js:5285:13)
error.ts:9 
        
       Uncaught (in promise) ElementPlusError: [ElBacktop] target does not exist: .app-main .el-scrollbar__wrap
    at throwError (error.ts:9:9)
    at use-backtop.ts:43:9
    at runtime-core.esm-bundler.js:2739:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2713:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
    at flushJobs (runtime-core.esm-bundler.js:397:9)
```
在bar.tsx113行的代码如下
``` TS
              <div class="flex mr-4">{slots?.buttons()}</div>
```

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/151592c660ae15c814e75b992576c3d632b9a4b8)
